# Generated by Django 3.2.9 on 2021-12-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20211210_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcomment',
            old_name='comment_id',
            new_name='replycomment',
        ),
    ]
