# Generated by Django 3.2.9 on 2021-12-11 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_rename_comment_id_subcomment_replycomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcomment',
            options={'ordering': ('-created',)},
        ),
    ]
