# Generated by Django 3.2.9 on 2021-12-11 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_subcomment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomment',
            name='parent',
        ),
    ]
