# Generated by Django 3.2.10 on 2021-12-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_alter_post_header_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header_image',
            new_name='image',
        ),
    ]
