"""
Django settings for vaultproject project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import hvac
import json
import vaulthelpers



myjsonfile=open('env.json','r')
json_data=myjsonfile.read()
obj=json.loads(json_data)
print("Data -- ",obj)

VAULT_URL = obj['VAULT_URL']
print("ans",VAULT_URL)
VAULT_SKIP_VERIFY = obj['VAULT_SKIP_VERIFY']
VAULT_DEBUG = obj['VAULT_DEBUG']
VAULT_TOKEN = obj['VAULT_TOKEN']
VAULT_ROLEID = obj['VAULT_ROLEID']
VAULT_APPID = obj['VAULT_APPID']
VAULT_SECRETID = obj['VAULT_SECRETID']
VAULT_AWS_PATH = obj['VAULT_AWS_PATH']
VAULT_USERID = obj['VAULT_USERID']
VAULT_DATABASE_PATH = obj['VAULT_DATABASE_PATH']
DATABASE_URL = obj['DATABASE_URL']



client = hvac.Client()
client = hvac.Client(url=VAULT_URL,token=VAULT_TOKEN)
#client.write('secret/snakes', type='pythons', lease='1h')
#client.write('secret/snake', type='pythons', lease='1h')
# print("url, token =",VAULT_URL,VAULT_TOKEN)
print("secrett -- ",client.read('secret/snakes'))
print("AWS -- ",client.read('aws/creds/my-role'))
# print("client=",client, client.is_authenticated())





# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mil%@u+7wf)5n^yj0#6xmxwjba_vjf(ocohqgwaq$-ll(f)1_c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'vaulthelpers',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vaultproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vaultproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': vaulthelpers.database.get_config({
        'ATOMIC_REQUESTS': True,
        'CONN_MAX_AGE': 3600,
    }),
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
